nc: 16
depth_multiple: 0.25
width_multiple: 0.40

anchors:
  - [10,13, 16,30, 33,23]  # P3/8
  - [30,61, 62,45, 59,119]  # P4/16
  - [116,90, 156,198, 373,326]  # P5/32

backbone:
  # [from, number, module, args]
  [[-1, 1, Conv, [64, 3, 2]],  # 0-P1/2
   [-1, 1, Conv, [128, 3, 2]],  # 1-P2/4
   [-1, 3, C2f, [128, True]],
   [-1, 1, Conv, [256, 3, 2]],  # 3-P3/8
   [-1, 4, C2f, [256, True]],
   [-1, 1, Conv, [512, 3, 2]],  # 5-P4/16
   [-1, 4, C2f, [512, True]],
   [-1, 1, Conv, [1024, 3, 2]],  # 7-P5/32
   [-1, 2, C2f, [1024, True]],
   [-1, 1, SPPF, [1024, 5]],
  ]

head:
  [[-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 6], 1, Concat, [1]],  # cat backbone P4
   [-1, 2, C2f, [512]],

   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [[-1, 4], 1, Concat, [1]],  # cat backbone P3
   [-1, 2, C2f, [256]],

   [-1, 1, Conv, [256, 3, 2]],
   [[-1, 12], 1, Concat, [1]],  # cat head P4
   [-1, 2, C2f, [512]],

   [-1, 1, Conv, [512, 3, 2]],
   [[-1, 9], 1, Concat, [1]],  # cat head P5
   [-1, 2, C2f, [1024]],

   [[15, 18, 21], 1, Detect, [nc]],  # Detect(P3, P4, P5)
  ]

optimizer:
  name: 'SGD'
  lr: 0.01
  momentum: 0.937
  weight_decay: 0.0005

lr_scheduler:
  name: 'cosine'
  warmup_epochs: 3
  warmup_momentum: 0.8
  warmup_bias_lr: 0.1

augmentation:
  hsv_h: 0.015
  hsv_s: 0.7
  hsv_v: 0.4
  translate: 0.1
  scale: 0.5
  fliplr: 0.5
  mosaic: 1.0
  mixup: 0.1

# Training settings
epochs: 100
batch_size: 16
img_size: [448, 448]
multi_scale: False
nbs: 64
accumulate: 1
amp: True 